export const ACTION_GET_ITEMS_STARTED = 'GET_ITEMS_STARTED';
export const ACTION_GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS';
export const ACTION_GET_ITEMS_ERROR = 'GET_ITEMS_ERROR';

export const ACTION_ADD_ITEM = 'ADD_ITEM';
export const ACTION_REMOVE_ITEM = 'REMOVE_ITEM';
export const ACTION_EMPTY_CART = 'EMPTY_CART';
export const ACTION_CHANGE_QUANTITY = 'CHANGE_QUANTITY';

export const ACTION_ADD_COUPON = 'ADD_COUPON';
export const ACTION_REMOVE_COUPON = 'REMOVE_COUPON';

export const ACTION_ADD_TO_HISTORY = 'ADD_TO_HISTORY';
